### ISSUE TITLE
vars like @name is still extracted

### ISSUE THREAD

**Issue by devmondo** [wiresjs/extract-vars#1]
example

```
dig(`@name callMe($$name)`)
```

we get back 
`name` and `$$name` as extracts.

**Comment by nchanged** [comment]
@name isn't a valid javascript expression, therefore fixing is redundant ;-)

**Comment by devmondo** [comment]
On second hand, i think we agree that that this is not valid JS, so the only reason for such a thing, is to use that as placeholder, in that case it is our job to handle it before using extract.
